### ISSUE TITLE
Add-On Charges

### ISSUE THREAD

**Issue by sean8300** [sean8300/listerassister_issues#115]
Under billing, need a new option that says "Add-On Charges"
Submitted By: Chad

**Comment by sean8300** [comment]
Assigning this to Juvi as a training lesson not on coding so much as communicating with others about requirements and getting clarity. 
This one is really old, does this ticket apply anymore?  Is this different than that add-on charge we currently have?

**Comment by Juvie92** [comment]
![image](https://user-images.githubusercontent.com/64864069/83901818-36449100-a710-11ea-960f-6ad9278d4eaf.png)
