### ISSUE TITLE
MLS Number

### ISSUE THREAD

**Issue by sean8300** [sean8300/listerassister_issues#181]
Need to know how many MLS' we have for the next business day.
Submitted By: Chad

**Comment by sean8300** [comment]
This would be run via query until built into site....may be good one for Juvi to work on

**Comment by Juvie92** [comment]
I created a query that will result in the count of listings that aren't closed and mls status is in queue.

SELECT COUNT(DISTINCT listing.id) 'MLS in queue'
FROM `listing_workflow_step`
INNER JOIN listing_workflow ON listing_workflow_step.listing_workflow_id=listing_workflow.id
INNER JOIN listing ON listing_workflow.listing_id=listing.id
WHERE `workflow_step_id` = 13
AND listing.status in ('new','processing')

I'm assuming next step is building it into the site. I'm probably gonna wait before tackling that.

**Comment by Juvie92** [comment]
SELECT DISTINCT(appointment_id), appointment.listing_id, appointment_service.service_type, appointment.scheduled_date FROM appointment_service
INNER JOIN appointment ON appointment_service.appointment_id=appointment.id
INNER JOIN order_item ON appointment.listing_id=order_item.listing_id
INNER JOIN listing_workflow ON appointment.listing_id=listing_workflow.listing_id
INNER JOIN listing_workflow_step ON listing_workflow.id=listing_workflow_step.listing_workflow_id
WHERE service_type LIKE 'photos%'
AND appointment.scheduled_date='2020-06-02'
AND order_item.description='MLS Entry'
AND removed_ts IS NULL
AND listing_workflow_step.workflow_step_id <> 29

**Comment by sean8300** [comment]
Q looks good, now we just need to know where to actually put this info.  Asked Chad, he said ask Greg, he said ask Nicole, asked Nicole and now waiting to hear back.  Will check again
