### ISSUE TITLE
Agent's office address added to information

### ISSUE THREAD

**Issue by sean8300** [sean8300/listerassister_issues#343]
We should add to the customer files a field where we can fill in a place for the office address for agents.  Putting in standing instructions just adds more junk to read but if we put in a field under the customer profile we know where to find that information if we need it for that agent. 

Submitted By: Kate

**Comment by sean8300** [comment]
Cant tag who submitted it because they aren't here anymore, going to tag Nicole instead so she can monitor.  This is a great one for Juvi to work on

**Comment by Juvie92** [comment]
Validate state input. Should only be 2 digit and uppercase. Zip code only 5 characters long.

**Comment by Juvie92** [comment]
ALTER TABLE customer
ADD address varchar(100),
ADD city varchar(70),
ADD state varchar(2),
ADD zip_code varchar(10);
