### ISSUE TITLE
Add Advanced Editing Photos to Website. 

### ISSUE THREAD

**Issue by sean8300** [sean8300/listerassister_issues#388]
Add Advanced Editing Photos to Website please, preferably so they show before what's already there:  https://1drv.ms/u/s!AqLylZLphekujtdQHBHvDl0FMuGEQA?e=yjdbV6 
 Submitted By:  Nelson Tello

**Comment by sean8300** [comment]
This is an update to the front end of the site, should be pretty quick/easy

**Comment by Juvie92** [comment]
Looks like this was done already. Did change the order of the photos to match up with how they were in the Onedrive folder.

**Comment by sean8300** [comment]
Confirmed this was done on front end with Juvi, good to close
