### ISSUE TITLE
Agent Lic # on Marketing

### ISSUE THREAD

**Issue by sean8300** [sean8300/listerassister_issues#430]
Please add agent lic # to marketing  
 Submitted By:  Nicole Sourant

**Comment by sean8300** [comment]
This should actually be pretty quick and easy, going to assign it to Juvi as its a great one to get feet wet

**Comment by sean8300** [comment]
1 - where should it appear (website, VTs, flyer, all, none, some, etc)
2 - Show the license # field on the customer tab of listing details
3 - Keep in mind that no matter where you put this field it will have to be set to not show anything if its not filled out, so sometimes it will be visible and sometimes not, and many of the marketing items (espec the flyer and virtual tour) are precisely sized, so you will have to take that into account

**Comment by Juvie92** [comment]
Hello Nicole, I'm looking at the ticket you submitted about adding agent license number in marketing. Can I get some clarification about that? Where in marketing do you want the number added? Thank you.

Nicole's Response:
Hello, We need the agent's license number to be added to the marketing material in the same area that their brokerage/contact info is displayed. Our registration form asks them for their license number, some agents use it and some dont so if they provide it, it needs to be on the marketing material but if they dont provide it I hope that it wont look weird.

**Comment by sean8300** [comment]
Juvi completed
