### ISSUE TITLE
Duplicate Item Bug

### ISSUE THREAD

**Issue by sean8300** [sean8300/listerassister_issues#470]
I found that when needing to charge for more than one item through the work order. it will reflect duplicates of the last item selected and not the multiple items you selected. See tab on WO #164899. The 2nd payment tab was for $217.00 for 25 Photos and Virtual Staging on 2 rooms, The tab just shows Virtual Staging Twice, Nowhere doe sit show 25 Photos. This is going to be very confusing to customers 
 Submitted By:  Meghan Levy

**Comment by sean8300** [comment]
It looks like it is charging the customer the correct amount, which is the most important thing.  It is then displaying the incorrect amount in the listing details.  This is def a bug, but its not a common and game breaking bug so may not be able to address it for quite some time.  Will update ticket when more info becomes available or when I begin working on this

**Comment by sean8300** [comment]
Keeping this one as the main bug tracker, closing others related to this and linking back to here

**Comment by Juvie92** [comment]
![image](https://user-images.githubusercontent.com/64864069/83929010-a968fa00-a746-11ea-8ecb-63cbdbb1623c.png)

Success! I commented out the bits that have to deal with credit info validation and authorization and whatnot to test.

**Comment by sean8300** [comment]
This is same as #488 closing that one, this one stays open
