### ISSUE TITLE
Customer brokerage

### ISSUE THREAD

**Issue by sean8300** [sean8300/listerassister_issues#482]
Have new field for company brokerage but the list of avail brokerages will be provided so customers will select from a dropdown.  Dont have list yet so not ready to deploy, should be able to start building though 
 Submitted By:  Sean O'Donnell

**Comment by sean8300** [comment]
Spoke with Chad about this.  Probably have Juvi start on it, good experience doing an ajax select, still have to figure out details with Chad (such as which brokerages go in the list right now, how do we add more in the future, what happens when customer is trying to sign up and its not listed, etc)

**Comment by Juvie92** [comment]
Brokerage field changed to an ajaxselect field. 
Customers can not change their brokerage, it is a disabled input field.
When registering this field can be left blank if their broker does not appear as an option.

**Comment by sean8300** [comment]
Please review notes in pull request 
https://github.com/sean8300/listerassister/pull/569
