### ISSUE TITLE
Text Box for Removals

### ISSUE THREAD

**Issue by sean8300** [sean8300/listerassister_issues#484]
Please create a text box that states "Are there any special instructions or additional items we need to grab ?"  where agents can state any additional items they may have at the property that they want us to pick up, but that we did not install. they can also place special instructions like if the post is on side of the house or any lock box cbs and shackle code info. Since I been doing removals I noticed I spend a lot of time going back and forth with agents about additional inventory needing to be picked up that we did not install. Often the email comes in from them after they have discontinued the services because there is no option.  I think if when they discontinue the service we add in the box its a chance to get all the info at once for what needs to be removed and will save us a lot of time in the future.

 
 Submitted By:  Meghan Levy

**Comment by sean8300** [comment]
Juvi:
For this log in as Leonard cooper, select a property and click the red Discontinue All Services along the bottom.  
What we are looking for here is to add the text box referenced in the tix to this area.

It would have to do a few things:
A, capture that information via a log/note, look at other logs generated from a customer for how to do that (its all on the same service, just have to access the customer var a little differently)
B, it would have to create a group instruction.  This can be tricky because the group instructions get wiped during this process, so prolly want to assign the new note to a variable, wipe the notes, then re-add the var as a note
C, it would send a removal email TO US.  Get with Meghan to see which email it should go to and what t he email should say.  Be prepared to also have them ask if you could include which inventory items are attached to the property in this email 
D, update the ticket with what Meghan tells you
E,......actually I think thats it.  Capture info, save info, email info.

**Comment by Juvie92** [comment]
Additional comments from Meghan Levy:

That is correct, when someone clicks to discontinue services, the email generates and comes through to Removals@listerassister.com
Whatever they place in that text box, needs to also be included in the email that comes through to the removals inbox
that way when I schedule the remove I know right then and there what all needs to be removed to I can property notate it for the installer or photographer and get it all done in one shot
