### ISSUE TITLE
In System Refunds

### ISSUE THREAD

**Issue by sean8300** [sean8300/listerassister_issues#485]
Want to actually process refunds through the system.  This will allow the dashboard to display more accurate revenue, right now its totally blind to refunds and we have a TON of refunds this year, really throwing things off
1 - I have to figure out exactly how to issue a refund through the Authorize API.  Obviously not going to do this to a real customer so I may have to create an order on my company CC and practice refunding money back (like charge $100, refund $1 at a time to learn it, etc).  2 - How to subtract that number from the dashboard.  With any luck I can just create a new order item with a negative value.....actually coupons do exactly that, so real question is if the order TOTAL can be a negative instead of line item.....if so then I may be able to send a negative value (or a positive "refund" value) to Authorize and capture that amount in the system 
 Submitted By:  Sean O'Donnell

**Comment by sean8300** [comment]
This is going to ONLY be refunds that were charged through Authorize, will not be tracking refunds for invoices

**Comment by sean8300** [comment]
First part (researching API) done, waiting to be given thumbs up to begin the ACTUAL implementation of this

**Comment by Juvie92** [comment]
This is similar to ticket #697 which has already been addressed and closed so doing the same to this.
