### ISSUE TITLE
Services In Add Order (Charge) List

### ISSUE THREAD

**Issue by sean8300** [sean8300/listerassister_issues#512]
Hello, I am finding that some services I charge for pretty often do not have their own selection in the drop-down menu, therefore I typically select other, then type into the description box what we are charging for. Example: Photo Upgrade, because we do not have a photo upgrade service in the list I have to place these under "other". Should I be submitting a tix whenever I want to add a service? If so for now please add the following:

Photo Upgrade
H Frame Upgrade
MLS - Description Only
 
 Submitted By:  Meghan Levy

**Comment by sean8300** [comment]
This is kinda tricky, the values in that dropdown list are populated from our actual products list, they aren't manually typed in (and during submission those values are checked to make sure they are in fact actual products, so cant force things in).  Though adding these as actual products is a possibility, I'm afraid of our products list growing to a huge list of "one off" things.  

For right now putting a pin in this for now

**Comment by sean8300** [comment]
Spoke with Meghan, she was going to provide a list of items to have in the list

**Comment by Juvie92** [comment]
Sent a google sheet with the products in this list. Meghan has made some changes but I'm not sure if its ready to go yet. Will message her and ask if she is still reviewing this list.

**Comment by Juvie92** [comment]
Based off changes requested by Meghan, I've created some queries to update the 'product' table.

```
UPDATE product SET name = "On Site Cancellation", nice_name = "Fee - On Site Cancellation" WHERE id = 123;
UPDATE product SET code = "trip_fee", name = "Trip Fee", nice_name = "Fee - Trip Fee" WHERE id = 125;
UPDATE product SET name = "Flyers", description = "", nice_name = "Flyers" WHERE id = 7;
UPDATE product SET code = "virtual_staging", name = "Virtual Staging", nice_name = "Virtual Staging" WHERE id = 40;
UPDATE product SET is_deleted = 1 WHERE id in (17,141,142,39,87,45);
UPDATE product SET is_addon = 0 WHERE id in (76,77,78,79,80,81,82,83,84,85);
UPDATE product SET nice_name = "Marketing - Walkthrough" WHERE id = 61;
UPDATE product SET nice_name = "Marketing - Walkthrough Enhanced" WHERE id = 152;

```

```
INSERT INTO product (code, name, price, is_addon, nice_name, is_deleted, is_fee) Values ('service_cancelation','Specialty Service Cancelation',0,1,'Fee - Specialty Service Cancelation', 0, 1);
INSERT INTO product (code, name, price, is_addon, nice_name, is_deleted, is_fee) Values ('inventory_pickup','Inventory Pickup',0,1,'Fee - Inventory Pickup', 0, 1);
INSERT INTO product (code, name, price, is_addon, nice_name, is_deleted, is_fee) Values ('additional_photos','Additional Photos',0,1,'Additional Photos', 0, 0);
INSERT INTO product (code, name, price, is_addon, nice_name, is_deleted, is_fee) Values ('matterport-sqft-charge','Additional SqFt Matterport Charge',0,1,'Matterport - Additional Sqft', 0, 0);
INSERT INTO product (code, name, price, is_addon, nice_name, is_deleted, is_fee) Values ('additional_editing','Additional Editing',0,1,'Additional Editing', 0, 0);
INSERT INTO product (code, name, price, is_addon, nice_name, is_deleted, is_fee) Values ('sky_drops','Sky Drops',0,1,'Sky Drops', 0, 0);
INSERT INTO product (code, name, price, is_addon, nice_name, is_deleted, is_fee) Values ('2d_floorplan','2D Floorplan',0,1,'2D Floorplan', 0, 0);
INSERT INTO product (code, name, price, is_addon, nice_name, is_deleted, is_fee) Values ('order_correction','Order Correction',0,1,'Order Correction', 0, 0);
INSERT INTO product (code, name, price, is_addon, nice_name, is_deleted, is_fee) Values ('photo_upgrade','Photo Upgrade',0,1,'Photos - Photo Upgrade', 0, 0);
INSERT INTO product (code, name, price, is_addon, nice_name, is_deleted, is_fee) Values ('photo_downgrade','Photo Downgrade',0,1,'Photos - Photo Downgrade', 0, 0);
INSERT INTO product (code, name, price, is_addon, nice_name, is_deleted, is_fee) Values ('mls_description_entry','MLS Description Entry',0,1,'MLS - Description Only', 0, 0);
```

**Comment by sean8300** [comment]
UPDATE product SET name = "On Site Cancellation", nice_name = "Fee - On Site Cancellation" WHERE id = 131;
UPDATE product SET code = "trip_fee", name = "Trip Fee", nice_name = "Fee - Trip Fee" WHERE id = 130;
UPDATE product SET name = "Flyers", description = "", nice_name = "Flyers" WHERE id = 7;
UPDATE product SET code = "virtual_staging", name = "Virtual Staging", nice_name = "Virtual Staging" WHERE id = 40;
UPDATE product SET is_deleted = 1 WHERE id in (17,39,64,45);
UPDATE product SET is_addon = 0 WHERE id in (87,89,90,91,92,93,94,95,96,88);
UPDATE product SET nice_name = "Marketing - Walkthrough" WHERE id = 61;
UPDATE product SET nice_name = "Marketing - Walkthrough Enhanced" WHERE id = 164;

**Comment by sean8300** [comment]
Qs updated to match live values and ran on live db
