### ISSUE TITLE
Matterport/Zillow/Enhanced Zillow Bug

### ISSUE THREAD

**Issue by sean8300** [sean8300/listerassister_issues#513]
Your calculated checkout total does not match what is displayed. Please refresh the page and try again.648 - 911 
 Submitted By:  Jo  Thomas

**Comment by sean8300** [comment]
tested on dev, totals are different but getting same error.

**Comment by sean8300** [comment]
Suspect issue is with Matterport, having Juvi take a look so I can get this preopen house ready

**Comment by sean8300** [comment]
JUVI:  Look at Matterport first, suspect thats the problem, but be very conscience when messing around with the price triggers here, you don't want to break Prime when fixing this issue.  Order rebuild mimic the issue:

4400 SqFt
Essential
Large/Print Size
Advanced
55 Photos
Matterport 
Zillow Walkthrough (this may also be the point of failure, but considering price I think its Matterport)

**Comment by Juvie92** [comment]
If advanced was selected along with large images, system didn't take into account that advanced includes large images(hi res). Changed it to where its ignored if large images is selected along with advanced.

**Comment by sean8300** [comment]
Updated the pull request, prior code added hires when advanced was selected, system shouldn't be doing any additional checks on top of that.

**Comment by sean8300** [comment]
This came up again today, someone ordered Essential (which doesnt come with Matterport) and added a matterport, its giving the wrong checkout totals

**Comment by sean8300** [comment]
@Juvie92 
I was planning on leaving this for you but we had this come up a bunch of times, so had to go in and fix it.

This is done and fixed, have you tagged for you to see the changes that were made.

First I moved the $sqFt variable to line 687, this was it is set once (for each property) and forgotten, previously it was being constantly set and overriding itself, which was unneeded.

Second starting at line 720 I cleaned up the IF statement.  All we need to know here is if the SqFt is over the limit, and adding to the price if so.  Everything else that was there was redundant, and the setting to $0 at the end was not needed.  I believe you copied my previous code when doing the zillow and advanced zillow, so you were probably just copying my bad code. 

The price for these three services (matterport, zillow, enhanced zillow) was also hardcoded to be $0 at some point, which was also unneeded. 

When done reviewing please close this ticket
