### ISSUE TITLE
Las Vegas Posts

### ISSUE THREAD

**Issue by sean8300** [sean8300/listerassister_issues#531]
When I go to add this to order from inventory it also says there are none available, even though mitch explained to me that there are some available.  
 Submitted By:  Jaciana Alvarez Carrillo

**Comment by Juvie92** [comment]
Getting clarification from Jaciana. Assuming its this:
![image](https://user-images.githubusercontent.com/64864069/87185063-fb4cf480-c29d-11ea-9173-d4f5a18331dd.png)

**Comment by Juvie92** [comment]
![image](https://user-images.githubusercontent.com/64864069/87185351-731b1f00-c29e-11ea-91fa-35b657d759ef.png)
