### ISSUE TITLE
wrong price charged

### ISSUE THREAD

**Issue by sean8300** [sean8300/listerassister_issues#538]
Order #174295  Essential Listing 40 photos should have been  194.00 C21 discount  should have charged  159.00 +  Zillow walkthrough  99.00  TOTAL Charge should have been   258.00. Am I missing something?   
 Submitted By:  Maria O'Donnell

**Comment by Juvie92** [comment]
The C21NW code is a $85 discount (unless that amount is off). After reviewing the items on order #174295 and applying the discount, the total is $208, which is what it shows on the order. Messaging Maria and might need to make sure that amount for the discount is correct.

**Comment by Juvie92** [comment]
![image](https://user-images.githubusercontent.com/64864069/86856255-cc9e0680-c070-11ea-8902-5e1e9218d164.png)
