### ISSUE TITLE
Billing Status Trigger

### ISSUE THREAD

**Issue by sean8300** [sean8300/listerassister_issues#542]
Please remove the ability to add a billing group instruction and create something that triggers the note and the billing status in one? 
 Submitted By:  Nicole Sourant

**Comment by sean8300** [comment]
I think this tix wasn't very clear.  

The billing status dropdown is entirely blocked out, this shouldn't happen. Don't think this field should be touched at all.

When you click the Add button next to Group Instructions in the listing details screen you get a "Add Instruction" field.  Remove "Billing" as an option in that dropdown.

From the billing status dropdown if "Needs X" (invoice, refund, billing) is selected then we need some type of note popup that requires information be added so that when we say needs invoice the reps are forced to tell billing what to put on the invoice.  The note that gets entered here should create a Billing group instruction on the invoice.  

So Billing removed from group instruction, the new way to add a billing note is when changing the billing status.  All other note types get entered the same way.

**Comment by sean8300** [comment]
Please see PR for info https://github.com/ListerAssister/dashboard/pull/607

**Comment by sean8300** [comment]
Meghan IM'd to let me know that when you chage to Paid it doesn't show the instructions box (as intended) but it still creates a group instruction...just a random blank group instruction.

**Comment by Juvie92** [comment]
This is a tough one to diagnose. Trying it on my local server didn't create the billing instruction. Even trying the local server on chrome didn't create it. Decided to be a bit more explicit when dealing with the instructions and see how that works on live.
