### ISSUE TITLE
Order 168567 - Sellers email link to property website

### ISSUE THREAD

**Issue by sean8300** [sean8300/listerassister_issues#546]
Link to property website inside of sellers email brings you to listerassister homepage instead. Thank You! 
 Submitted By:  Lara Jones

**Comment by Juvie92** [comment]
I remembered seeing an email about this over the weekend and used that to try some stuff out.
I found out that the link on that particular email is wrong.
https://4039-w-eva-st.properties.listerassister.com%20   (need to remove the %20)

I then decided to look up the link on our flyer for that property and it had:
http://4039-w-eva-st.properties.listerassister.com            (works after changing http to https)

We need to gather more info over this issue but I'm assuming the biggest issue is the "http".
Going to message Lara to see if she has more info.

**Comment by Juvie92** [comment]
Didn't realize there was an order number on this issue.

After checking the flyer for order 168567 it had the same 'http' issue and changing it too 'https' fixed it.
Need to check where the link is created.

**Comment by Juvie92** [comment]
Got a message from Lara about another agent that brought this to her attention. WO# 176730.

**Comment by Juvie92** [comment]
Another agent brought this issue up for WO#173021

**Comment by Juvie92** [comment]
Going to take another look at this. Changing the 'custom' url to the direct url to the property website.
