### ISSUE TITLE
WO Reflection of charges

### ISSUE THREAD

**Issue by sean8300** [sean8300/listerassister_issues#551]
#173642 - Agent was concerned we charged him twice because WO total reflects totals of 2 matterports and 25 photos. Maria charged the order through the system after we pushed it through for the agent ( which we are not supposed to do) and so now it shows two matterports. I need this correct for agent records
 
 Submitted By:  Meghan Levy

**Comment by Juvie92** [comment]
Another one that needs values updated/changed in the database. Don't have access to it but will create a query for Sean to use if he deems it necessary.

**Comment by Juvie92** [comment]
UPDATE order_item
SET price = 0.00
WHERE listing_id = 173642
AND order_id = 115483
AND description LIKE '%Matterport%'

**Comment by sean8300** [comment]
This is a bigger issue, paying for invoices through the dashboard add-on charge.  Will not be artificially modifying the numbers
