### ISSUE TITLE
Update Email ASAP

### ISSUE THREAD

**Issue by sean8300** [sean8300/listerassister_issues#576]
Please update the verbiage in the confirmation email. 

Currently : Please note that cancellation of this appointment by yourself or the client after 5 PM the business day prior to the appointment (Friday for a Monday appointment) will result in a $79 cancellation fee. This is an automatically generated email.

Update : Please note that cancellation of this appointment by yourself or the client after 5 PM the business day prior to the appointment (Friday for a Monday appointment) will result in a $89 cancellation fee. This is an automatically generated email. 
 Submitted By:  Nicole Sourant

**Comment by Juvie92** [comment]
Noticed there are different messages generated based on what the order consists of. This $79 fee is generated if order has twilight. I'm assuming its that but messaged Nicole to verify.

**Comment by Juvie92** [comment]
![image](https://user-images.githubusercontent.com/64864069/87606514-02b23a80-c6b0-11ea-8d1c-f874fc897a32.png)

**Comment by Juvie92** [comment]
Changed fee value on the email template. For both my local and live sites.
