### ISSUE TITLE
sub orders

### ISSUE THREAD

**Issue by sean8300** [sean8300/listerassister_issues#577]
can suborders have the same parent to child order details.  
 Submitted By:  Whitney Wellito

**Comment by Juvie92** [comment]
Need to pass through orders for original order but need to make sure that suborders don't have orders of there own.

More like need to add a check if listingId is original or sub. If not original, use original to get orders.

**Comment by sean8300** [comment]
Spoke with Juvie really quick, might want to get clarity on what this is asking for.  The child will always make reference to the parent, but the parent is not necessarily the original.  The original should always be listed, but you can have a chain of child/parent orders under neath it, and no matter how deep that goes the child will always point to the parent, not the original. Juvie said he would get clarification

**Comment by Juvie92** [comment]
![image](https://user-images.githubusercontent.com/64864069/87860343-99ba0500-c8f1-11ea-82a6-29ea12240237.png)

**Comment by Juvie92** [comment]
Need to clarify with Sean but issue might actually be the purpose of sub-orders and how they are used. It seems to me that they are meant for installations.

**Comment by sean8300** [comment]
Sub orders aren't ONLY for installations, other things (like drones, etc) can get split off.

You can have multiple appointments on a work order, BUT, a work order can only be on ONE route.  So if we have a photographer doing photos and Tuesday and a drone person doing drone PV on Wednesday we cannot have this on the same work order because these would be on two different routes: hence, suborders.

**Comment by Juvie92** [comment]
Messaged Whitney letting her know that we won't be doing any work on this ticket. Issue wasn't about the suborder "order details". Waiting to hear back from her.

**Comment by Juvie92** [comment]
'ok' - Whitney
