### ISSUE TITLE
Computer set up for Johann

### ISSUE THREAD

**Issue by sean8300** [sean8300/listerassister_issues#578]
Johann will be coming back to do photo reviews for us. He is going to need a computer set up that can run light room and allow him to create simple videos. he will be taking this set up home (provided its approved by chad) wanted to get this to you as early as possible so we can get ahead of it.  
 Submitted By:  Mitchell Levy

**Comment by Juvie92** [comment]
Computer is set to go. 2 monitors with power cables and hdmi cables. Keyboard, mouse and tower set to go. Installed lightroom, photoshop, premiere pro and slack on there. Google chrome signed in as info@.
