### ISSUE TITLE
Marketing Contact Field

### ISSUE THREAD

**Issue by sean8300** [sean8300/listerassister_issues#580]
Marketing contact field is not overriding for marketing materials. 
 Submitted By:  Lara Jones

**Comment by Juvie92** [comment]
Messaged Lara for more information and she mentioned to get in contact with Meghan. Messaging her to try to get a clearer picture of what this is about exactly.

**Comment by Juvie92** [comment]
![image](https://user-images.githubusercontent.com/64864069/88416308-d3c55400-cd94-11ea-86cb-5de9b477f656.png)
