### ISSUE TITLE
Lockboxes Grouped

### ISSUE THREAD

**Issue by sean8300** [sean8300/listerassister_issues#592]
Would like the lockboxes to be grouped under Supra, but then show the individual numbers 
 Submitted By:  Chad O'Donnell

**Comment by Juvie92** [comment]
Needed some clarification where this was needed. Going to be on the client side.

![image](https://user-images.githubusercontent.com/64864069/89467039-ba73be80-d729-11ea-8874-90a93b634ba3.png)

**Comment by Juvie92** [comment]
The function that grabs the inventory for customer view doesn't take into account inventory items with owner id 'null', so no need to go through each lockbox and check if its a rental or not. I modified the 'filterCustomerDisplayDataRows'(in inventory service) function to skip the check if a customerID is provided, speeding up the load times.
