### ISSUE TITLE
Download Selected Photos Bug

### ISSUE THREAD

**Issue by sean8300** [sean8300/listerassister_issues#599]
When selecting photos and clicking 'download selected photos', error returns with no photos selected. 
 Submitted By:  Juvenal Navarro

**Comment by Juvie92** [comment]
Issue seems the same as an error I encountered earlier with the change classes button. Since I'm adding an additional class to each checkbox, the download button wasn't able to distinguish which boxes were checked because of that class change.

**Comment by sean8300** [comment]
Wasn't aware of the problem so not sure exact testing conditions (my testing of original passed), so assuming this is good and pushing
