### ISSUE TITLE
Change removal email to include WO#

### ISSUE THREAD

**Issue by sean8300** [sean8300/listerassister_issues#614]
Some already do, some only give cust # 
 Submitted By:  Sean O'Donnell

**Comment by Juvie92** [comment]
Not exactly sure which emails require changing. Messaged Sean for more info.

**Comment by Juvie92** [comment]
Checked removal emails that are sent when customer requests to stop services (one for removals@ and one for the customer) and they both have workorder numbers. Seems like this was already done before. Closing ticket
