### ISSUE TITLE
Remove "Free floorplan" from site on Matterport

### ISSUE THREAD

**Issue by sean8300** [sean8300/listerassister_issues#615]
Red text next to Matterport on order form
Also check front end
Make sure price sheet doesn't say anything about it 
 Submitted By:  Sean O'Donnell

**Comment by Juvie92** [comment]
I didn't see 2d floorplan mentioned anywhere else other than the order form as mentioned above. It was mentioned in the matterport email template but thats not in use yet and it has been removed from there.
