### ISSUE TITLE
Confirmation Emails?

### ISSUE THREAD

**Issue by sean8300** [sean8300/listerassister_issues#619]
can we possibly incorporate the time allotted for the appointment? Meaning we go to a property for 40 photos, matterport, drone video and install...we are there for about 3hours and 14 minutes give or take. Can we somehow include this so there's more open communication between the company and agents/clients? 
 Submitted By:  Breanna Stanford

**Comment by Juvie92** [comment]
Will need to update email template on live, but gonna hold off till ready to merge otherwise there would be a blank area that would cause confusion.
