### ISSUE TITLE
Refund through dashboard

### ISSUE THREAD

**Issue by sean8300** [sean8300/listerassister_issues#629]
See what it would take 
 Submitted By:  Sean O'Donnell

**Comment by sean8300** [comment]
Looks entirely doable, BUT it does actually look at the transaction that was submitted, so will need to A) have a transaction and B) refund an amount less than the original transaction amount

**Comment by sean8300** [comment]
Slacked Greg list

**Comment by sean8300** [comment]
Was on wrong issue when I closed :(

**Comment by Juvie92** [comment]
This is similar to ticket #697 which has already been addressed and closed so doing the same to this.
