### ISSUE TITLE
Matterport Charges

### ISSUE THREAD

**Issue by sean8300** [sean8300/listerassister_issues#631]
Talked to Nicole about this and she suggested I submit a ticket. We would like to discuss adding an option for agents to choose if there is an additional guesthouse ( or similar) at a property, whether it is attached or not attached, and how much sqft the extra area is, that way we can properly calculate at that time if more then one matterport scan will be needed and the proper cost for the service. 
 Submitted By:  Meghan Levy

**Comment by Juvie92** [comment]
Will need to contact Meghan about further information about this.
Need to figure out how much the additional charge would be or how it would be calculated. 

I'm also thinking this info can be gathered in the 'property details' slide and not just when agent adds matterport to order.

**Comment by Juvie92** [comment]
Meghan gave me a few more details about this issue. She mentioned that one idea that had been thrown around for this would be to disable the edit sqft field on customers side and have them call in to edit that. Everything can then be handled by CSR's (additional charges/service changes).

Again, something that may have to be discussed at managers meeting to see how to proceed with this.

**Comment by Juvie92** [comment]
Going forward with disabling sqft field and going to add a title telling customers to call in to change that.
