### ISSUE TITLE
Video Ready Email button not working.

### ISSUE THREAD

**Issue by sean8300** [sean8300/listerassister_issues#640]
The video/matterport ready email button may not be working (sending the actual emails) I have received several emails from agents asking where their stuff is and all of them have been sent through the video tab. I did a test using Leonard Cooper, sending myself the matterport links and it never arrived.  
 Submitted By:  Jessica Owen

**Comment by Juvie92** [comment]
Email codes for each email template needed to be updated. Tested on live and all seems good now.
