### ISSUE TITLE
Map on Employee Listing Details

### ISSUE THREAD

**Issue by sean8300** [sean8300/listerassister_issues#653]
Idea submitted by Brandon, when employees pull up listing details of a specific listing it should show a map with its location 
 Submitted By:  Sean O'Donnell

**Comment by Juvie92** [comment]
![image](https://user-images.githubusercontent.com/64864069/92778921-74c49a00-f356-11ea-80f7-ed64bbc2040f.png)

**Comment by Juvie92** [comment]
Will also be tackling issue #654 on this since they both deal with google maps.
