### ISSUE TITLE
Changing the Subject for Matterport emails

### ISSUE THREAD

**Issue by sean8300** [sean8300/listerassister_issues#656]
Is there any way we can update the matterport emails to have either the WO and address in the title or somewhere in the body of the email? Right now there is no way to tell what property the agent is referring to unless you click on the matterport link and go look at the address.  
 Submitted By:  Jessica Owen

**Comment by Juvie92** [comment]
Sent an example of what I have to Jessica. Just waiting on feedback/suggestions before applying it to live email-template.

**Comment by Juvie92** [comment]
Changes approved. Updated email-template on live.
