### ISSUE TITLE
High and Regular Res Images

### ISSUE THREAD

**Issue by sean8300** [sean8300/listerassister_issues#657]
Create a way to provide both hi-res and regular res from our site. 
 Submitted By:  Juvenal Navarro

**Comment by Juvie92** [comment]
Ability to upload hi-res images seems to be already there. It takes longer but all photos upload and show on the workorder I tested on local. Need to test a few times on live (in test wo's) to make sure all images upload properly.

Managed to get photos to scale down properly whether they are landscapes or portraits. 

Branded images always scale down to 1600x1067. May need to replicate function that creates those and adjust pixel values in that to create hi-res branded images if those are needed. Seemed we didn't provide those as is so need to see if there is demand for those.

**Comment by Juvie92** [comment]
Went about this a different way. Still gonna upload hi-res on dropbox but will provide a High Resolution button for customers to click on their dashboard.

Noticed that the email for 'photos ready' only include a link to customers dashboard so won't include link to dropbox in there. This can be changed in the future.

**Comment by sean8300** [comment]
This is probably being shelved, closing tix
