### ISSUE TITLE
Virtual Staging

### ISSUE THREAD

**Issue by sean8300** [sean8300/listerassister_issues#662]
There are times when Virtual Staging is canceled or just not needed.  Can you create a drop down that says "Not Needed"?
Thank you 
 Submitted By:  AnnMarie Romeo-Frost

**Comment by Juvie92** [comment]
Will need a database update.
Added a workflow step for virtual staging for "not needed". 

```
INSERT INTO `workflow_step` (`id`, `workflow_id`, `description`, `is_first`, `is_problem`, `is_complete`, `code`, `display_order`, `payout`) VALUES (NULL, '8', 'Not Needed', '0', '0', '1', 'vt_not_needed', '5', '0');
```
