### ISSUE TITLE
Customers can download internal images

### ISSUE THREAD

**Issue by sean8300** [sean8300/listerassister_issues#665]
When downloading all photos from customer side, they download all photos for that listing including photos with the 'internal' class. 
 Submitted By:  Juvenal Navarro

**Comment by Juvie92** [comment]
Excluded 'internal' class photos from downloading when the client downloads all photos for a listing. 

I'm thinking of packing 'installation' and 'removal' photos into a single folder within the zip file. Would help keep things a little more organized.
