### ISSUE TITLE
Add Chris to Audit Bar

### ISSUE THREAD

**Issue by sean8300** [sean8300/listerassister_issues#670]
Please add Chris in CSR to the audit bar  
 Submitted By:  Breanna Stanford

**Comment by Juvie92** [comment]
Messaged Bre about what 'audit bar' she means. The audit button in routes grabs the adminId automatically based on who's logged in. Waiting on response...

**Comment by Juvie92** [comment]
![image](https://user-images.githubusercontent.com/64864069/94594915-f2394700-023e-11eb-9fd0-f44e90f83717.png)

**Comment by Juvie92** [comment]
Chris' role (time access) has been updated and should now have access to scheduling note area.
