### ISSUE TITLE
marketing email is not showing that all links are being sent 

### ISSUE THREAD

**Issue by sean8300** [sean8300/listerassister_issues#674]
Marketing email is only showing that Flyer is being sent ,  noticed it on this one  WO#  185288  
 Submitted By:  Maria O'Donnell

**Comment by Juvie92** [comment]
Only showed as flyer being sent because website was not marked as published. 
Noticed all links still get sent but won't work if either flyer or website is not marked as published. May need to look further into this in the future. 
Closing this.
