### ISSUE TITLE
Add Post Install Reimbursement to Dash

### ISSUE THREAD

**Issue by sean8300** [sean8300/listerassister_issues#681]
Add Post Install Reimbursement to Dash 
 Submitted By:  Nicole Sourant

**Comment by sean8300** [comment]
Get with Nicole and make sure you understand the requirement here, *sounds* like we need to track each individual install and provide a bonus for it, which will require some pretty heavy changes/additions, but it could also simply easy as easy as a trigger like truck reimburse that increases the amount paid regardless of how many were installed

**Comment by Juvie92** [comment]
Got this working similar to how vehicle reimbursement works. Not going to be tracking how many posts are installed per person.
Will need to update the 'install_reimbursement' column for all employees that will be getting that. Waiting on Nicole for a list of those people and will attempt to create a query to update that.

**Comment by sean8300** [comment]
Updated the live DB with all current install ppl, according to what I was provided in https://docs.google.com/spreadsheets/d/1VIgbOd7WhoJJmJg-R_wbjkJUpLKonANDUMnQ0Phx9vQ/edit?usp=sharing
