### ISSUE TITLE
Item transfer issue

### ISSUE THREAD

**Issue by sean8300** [sean8300/listerassister_issues#686]
When trying to transfer an item, it stays in the original account - does not transfer item.  
 Submitted By:  Mitchell Levy

**Comment by Juvie92** [comment]
Abner tried transferring an item from a client account to another and it wouldn't work. Need to look further into this and see if there is anything on our side that may need fixing.

**Comment by Juvie92** [comment]
I've transferred a lockbox, a rider, and a sign between test accounts and no issues. Maybe this is something specific with the accounts used or item that needed to be transferred? 
I will try to see if Mitch can get that info from Abner but seeing this was from over a week ago I'm not sure he will remember.

**Comment by sean8300** [comment]
1 - look at the customers account and make sure its not disabled or anything, could interfere with process
2 - with signs you have to remember there are sign types, if you transfer Sign A to a different customer and new customer doesn't have Sign A TYPE associated with their account it will probably fail (dunno if thats the problem here just offering something to check)

**Comment by Juvie92** [comment]
We weren't able to get more info on this to look further into it. Going to close this but need to keep an eye out in case more like this pops up.
