### ISSUE TITLE
Receipt on Dashboard

### ISSUE THREAD

**Issue by sean8300** [sean8300/listerassister_issues#688]
When an agent goes in their dashboard, clicks a property, clicks the tab for order details, and then clicks the option in the top right corner for "print paid/invoice receipt." The Payment area just lists N/A - Does not actually state PAID anywhere on it. Wondering if this can be changed to maybe show the last 4 of the card they payed with Example: Payment: Visa.. 6328. This would apply to orders paid at time of ordering through the dash and if possible for the add on charges we do through the system
 
 Submitted By:  Meghan Levy

**Comment by Juvie92** [comment]
Updated PR
