### ISSUE TITLE
Video Links Sent

### ISSUE THREAD

**Issue by sean8300** [sean8300/listerassister_issues#690]
It would be nice to have Video Links Sent confirmation under the Photos Sent confirmation under the Send Photos Ready Email button if that makes sense? Just something to let us know what we've sent in a readily visible spot. I can explain further if you feel that would be beneficial. Thanks guys! 
 Submitted By:  Brandon Pease

**Comment by Juvie92** [comment]
Since there are up to 4 different emails that may be sent for videos (different type of videos), I decided to create a block that updates when ever an email for a video gets sent.
