### ISSUE TITLE
Refund/Credit info showing in dash

### ISSUE THREAD

**Issue by sean8300** [sean8300/listerassister_issues#697]
Currently we do not have refunds being processed through the dash, nor do they reflect on work orders or in the agent dash. I would like to come up with a way we can refund the agent directly through the work order. Similar to the Add Order (charge) , but a button to refund the agent. This would allow us to refund it back straight through the system, it would create a separate tab in the charge overview that is listed as refund and shows the credited amount and what we are refunding for. In addition to this we also currently have no way to add a credit to an agent online account so when they check out online they can either a) click a box to apply their credit or b) the system automatically apply the credit they have available to their next checkout. We would obviously need this set up where I am the only one who can go in and add/edit/delete credits, agents would obviously have zero access to do that. But If when they logged in to their dash it showed they had a credit I think that ould be pretty cool and would be a good way to track the credits and when they are being used where as right now they are only tracked through notes and standing instructions and the amounts aren't actually tracked in system totals/reports. Would be nice if when they use the credit on an order it shows in the order details on the WO just like Discount codes do. 
 Submitted By:  Meghan Levy

**Comment by sean8300** [comment]
Is this the same as https://github.com/ListerAssister/issues/issues/485?

**Comment by Juvie92** [comment]
I believe so. #186 and #629 seem so as well.

**Comment by sean8300** [comment]
actually talking about this in our meeting right now.  So it looks like we need the ability to add a negative dollar value to reflect a refund, this should keep our reporting numbers in sync.  Reps will send refund requests to billing by changing the order status to Needs Invoice, billing will pick it up and either refund through dashboard (if paid through dashboard) or Authorize (if not paid through dashboard).  Billing will then add the negative value "add order" or refund or whatever you come up with here

**Comment by Juvie92** [comment]
What I  have right now allows refunds through the dashboard. 
So do we need a way of adding a negative value item to an order without it processing anything through authorize? In case it has already been done through the authorize website?
