### ISSUE TITLE
Funky order

### ISSUE THREAD

**Issue by sean8300** [sean8300/listerassister_issues#722]
so so weird order was placed on it told me HD video and ZW needed to be scheduled but only the ZW was ordered. 

Essential Listing
Drone - Aerial Video (Not Photos)
MLS Entry
Marketing - Tour, Prop Site, Flyer Template
25 Photos
Walkthrough Video
Regular Post ($0)

but it says to schedule HD video and a Walkthrough?
its like 3 orders in one..
Order #193681 Order #193682 Order #193683 
 Submitted By:  Breanna Stanford

**Comment by sean8300** [comment]
Thanks for grabbing @Juvie92, was going to assign this to you.  Guessing this has to do with recent changes to service names

**Comment by Juvie92** [comment]
Didn't close with PR approval
Closing now
