### ISSUE TITLE
Refunds for cards not saved in system

### ISSUE THREAD

**Issue by sean8300** [sean8300/listerassister_issues#723]
Meghan brought up that many agents do not save their cards on our system. Currently, the refund feature works for only cards that are saved. Need to see if we can grab card info (mainly last 4 digits) throught the system somehow. 
 Submitted By:  Juvenal Navarro

**Comment by Juvie92** [comment]
This may have to be wait till we update our system. The docs on Authorize.net are for the latest api and we aren't at that point yet. I tried guessing at it based off of those docs but nothing worked. 

Putting this on hold until further notice.
Updating Meghan on the situation as well.

**Comment by sean8300** [comment]
@Juvie92 authorize should let you issue refunds to transaction ID's, which is stored in the system.  Try approaching from that angle instead of just issuing funds directly to a CC

**Comment by Juvie92** [comment]
Spoke with Meghan about approaching this differently. She mentioned processing all refunds through the authorize website and having a feature to add refund info to each workorder. 
Going to adjust everything to that.
