### ISSUE TITLE
OPEN HOUSE

### ISSUE THREAD

**Issue by sean8300** [sean8300/listerassister_issues#743]
open house package price showing on CLIENT LOG IN SIDE OF DASHBOARD. shows on PRICING tab. Please remove. Also leanord cooper shows a OPEN HOUSE button. can you please check to make sure this is not the case on client log in side.  
 Submitted By:  Mitchell Levy

**Comment by Juvie92** [comment]
Also changing the 'add service' button to 'place order' per Ryan
