### ISSUE TITLE
Timecards

### ISSUE THREAD

**Issue by sean8300** [sean8300/listerassister_issues#744]
Currently, when you add a new punch or timecard it placed it at the bottom of the list. For example, if someone forgot to clock in and out on Tuesday, and I go in on Friday and add in the hours for Tuesday, it will place it at the bottom of the week. Something so small but when manager run through and check timecards it would be good to not  have one part of Wednesday in the middle and the 2nd half of Wednesday all th way at the bottom  
 Submitted By:  Meghan Levy

**Comment by Juvie92** [comment]
I asked Meghan to take a look at adjusted times and make sure that they ordered properly. Just waiting on verification before closing this.

**Comment by Juvie92** [comment]
Time punches on time cards seem to be ordered properly. Closing this.
